---
name: Revive
author: Syntaxious
description: Revive yourself or a player
version: 1.2.0
api: [1.12.0]
main: Revive/Main

commands:
    revive:
        description: Reive a player or yourself
        permission: cmd.revive
permissions:
    cmd.revive:
        default: op
        description: "Revive yourself o
